# Generated by Django 5.2.8 on 2025-11-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollars'), ('eur', 'Euros'), ('rub', 'Russian Rubles')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.PositiveIntegerField(verbose_name='Процент скидки')),
                ('coupon_id', models.CharField(blank=True, max_length=50, verbose_name='ID купона в Stripe')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Items.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='Items.OrderItem', to='Items.item', verbose_name='Товары в заказе'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка налога (%)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='ID налога в Stripe')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='Items.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
    ]
